### ISSUE TITLE
Gradebook link on Assignments page

### ISSUE THREAD

**Issue by bkgray** [DeckardLain/ON-Mod-Suite#11]
When ON-Mod is active, the link to the gradebook is wrong on the Assignments page.  It works as expected when launching the gradebook from the Bulletin Board page.

When I disable the script in TamperMonkey and reload the page, the Gradebook loads as expected.

See this screen recording: https://bit.ly/3hJED5u

**Comment by DeckardLain** [comment]
Thanks for reporting! The script originally fixed the link, which was broken on Blackbaud's end.  Now that Blackbaud fixed it, the script breaks the link.  v2.12.5 disables the original fix.
