### ISSUE TITLE
problems with ConvertGradYearToGradeLevel()

### ISSUE THREAD

**Issue by bkgray** [DeckardLain/ON-Mod-Suite#12]
I am seeing some odd behavior related to ConvertGradYearToGradeLevel().

The wrong grade level is now (in June) added to the student's contact card. It appears that this is calculated in GetGradeLevel() based on the current calendar month (in June or after, go to the next grade level up).

Choosing June 1 as the cut-of results in two different grade levels displayed in the student's profile header.  See image1.

I would prefer to be able to set a specific date to apply to that rule. (For us, it would be July 1.)

There is code at INDEX010 to support activating the addition of the grade level or not in the Settings menu, but the Settings menu does not display the option. See image2. I didn't see anything in the Developers Console that seemed relevant.

Script version 2.12.5
Windows 10
Chrome 91.0.4472

![image1](https://user-images.githubusercontent.com/1683475/120896652-1e843f00-c5e8-11eb-8e63-4c180de56d68.png)

![image2](https://user-images.githubusercontent.com/1683475/120896651-1e843f00-c5e8-11eb-8186-9b881bc9c77b.png)

**Comment by DeckardLain** [comment]
Sorry for the confusion!  First, you are correct that you can change [this](https://github.com/DeckardLain/ON-Mod-Suite/blob/bedb68a02abff389bf3c53fd61d127c1708c1b1b/ON%20Mod%20Suite.user.js#L1290) line in the GetGradeLevel() function to change the switchover date.  See the [Other Schools Setup wiki page](https://github.com/DeckardLain/ON-Mod-Suite/wiki/Other-Schools-Setup) for more potential hard-coded school-specific items that may need to be changed.

The INDEX010 section was originally designed for group roster pages, so there is a menu it creates there that allows users to select how they want the grad year and/or grade level displayed on the cards.  The function that converts the grad year was later reused to display the grade level next to student names on their profile pages, but there's no user setting to control how that area is displayed.  The idea was that profile pages have lots of space to display both grad year and grade level all the time, whereas roster cards could get cluttered.

**Comment by bkgray** [comment]
That makes sense.  I must have forgotten that I saw the menu on the roster page. I must have imagined it being an option on the settings page.

Thanks for the explanation.
