### ISSUE TITLE
People Finder tweak not working

### ISSUE THREAD

**Issue by bkgray** [DeckardLain/ON-Mod-Suite#13]
For the past few days, the People Finder tweaks are not working consistently (Those tweaks are: focus on the name field, press enter to select first user in the list, press digit N to select Nth user).

The only clue that I see is an error in the console, but it may not be relevant - it appears with the script active or not.

![image](https://user-images.githubusercontent.com/1683475/165159769-161a293b-5e54-4df2-87a8-ff0dad6db0d3.png)

**Comment by DeckardLain** [comment]
Sorry, I think I stealth-fixed it in 2.15.1.  Blackbaud changed the element ID, so this line should take care of it: https://github.com/DeckardLain/ON-Mod-Suite/blob/0c6108cdf1157a281724ea93d1621f26e8b0f86c/ON%20Mod%20Suite.user.js#L465

**Comment by bkgray** [comment]
I'm using the generic version of the script.  I updated it to 2.12.5. The corresponding line appears to be after line 388.

I added the line you indicated. The initial test looks good - it appears to be working again.  I'll keep testing it.

**Comment by DeckardLain** [comment]
Ah yeah, sorry, I'll update the generic version now.

**Comment by bkgray** [comment]
I just updated to generic 2.12.6.  It loos good to me.  

Thanks for the quick fix.
