### ISSUE TITLE
WYSIWIG expand button and starting height doesn't work

### ISSUE THREAD

**Issue by bdleblanc** [DeckardLain/ON-Mod-Suite#14]
I've set the starting height to different levels, and it doesn't change the size of the box. The "expand" button with the downward pointing arrows also doesn't expand the height. Wondering if maybe BB changed the coding on those boxes - any ideas?

(By the way, stumbling across this on the K-12 community is up there with my wedding day and the birth of my daughter as one of the best days I've ever had. Thank you SO much for this mod!)

**Comment by bdleblanc** [comment]
Couple of other things:
The ability to increase the size of the distribution group selection box doesn't seem to work either (might be the same issue as with the wysiwig notes)

Also, there is no option to display unread admissions official notes first that I can see:
![image](https://user-images.githubusercontent.com/116751577/198101621-3a926ca9-ce99-416f-b980-8496e8b0d4e8.png)

**Comment by DeckardLain** [comment]
Blackbaud did change some (but not all) of the boxes to use a different javascript plugin.  Where is the text box that doesn't work with the mod?  I'll see what I can do.

It also looks like Blackbaud made a slight change to the distribution list selection box as well, so it at least auto-sizes the width.  The default height is still not great, though, at least to me, so I'll update the mod to handle this.

Sorry, the unread admissions notes feature was removed at some point because Blackbaud added an actual filter for unread notes.  I'll need to update the mod feature list.

Thanks for pointing out all these things!  I haven't looked at some of them myself in over a year, so I wasn't aware of some tiny changes Blackbaud made.

**Comment by bdleblanc** [comment]
I’ve noticed it with both the official notes composition box and with things like reminders/confirmations in checklist items. For now I just commented out that whole section of code on my end, because it was also affecting my ability to scroll down in a box.

If you can figure out a way to display unread replies to official notes at the top again, it would still be helpful – the “unread” filter occasionally won’t show replies, even though the number indicates that it should be there.

While it’s on my mind, do you take requests? I have a couple of other tweaks that would be helpful for us. I’ve asked Blackbaud about them, and they have, predictably, gone nowhere. If you prefer I submit them through github let me know and I’ll be happy to do so.

Thanks!!


Brian LeBlanc  Admissions Support Specialist

Thales Academy developing classical thinkers
Thales Management | 4641 Paragon Park Rd; Raleigh, NC 27616
Phone: (919) 208-9782 | Fax: (919) 227-5974 | Admission FAQs<https://www.thalesacademy.org/admissions/admission-faqs> | Apply Now<https://www.thalesacademy.org/admissions/apply-now>


From: DeckardLain ***@***.***>
Date: Wednesday, October 26, 2022 at 2:19 PM
To: DeckardLain/ON-Mod-Suite ***@***.***>
Cc: bdleblanc ***@***.***>, Author ***@***.***>
Subject: Re: [DeckardLain/ON-Mod-Suite] WYSIWIG expand button and starting height doesn't work (Issue #14)

Blackbaud did change some (but not all) of the boxes to use a different javascript plugin. Where is the text box that doesn't work with the mod? I'll see what I can do.

It also looks like Blackbaud made a slight change to the distribution list selection box as well, so it at least auto-sizes the width. The default height is still not great, though, at least to me, so I'll update the mod to handle this.

Sorry, the unread admissions notes feature was removed at some point because Blackbaud added an actual filter for unread notes. I'll need to update the mod feature list.

Thanks for pointing out all these things! I haven't looked at some of them myself in over a year, so I wasn't aware of some tiny changes Blackbaud made.

**Comment by DeckardLain** [comment]
Yes, I'll take a look at those text boxes and unread official notes.

And yes, I'm happy to get feature requests!  Feel free to email me directly or create issues in GitHub.

Thanks!

**Comment by DeckardLain** [comment]
I _think_ this is mostly fixed in v2.16.0.
