### ISSUE TITLE
Display Contract Type ID number and Contract ID number

### ISSUE THREAD

**Issue by bdleblanc** [DeckardLain/ON-Mod-Suite#15]
Hi Scott! When you have a second to add a feature, I'd love to be able to access the Contract Type ID (and, if possible, the Contract ID) number directly from the Manage Contract Forms screen. I use these in advanced lists all the time and right now the only way to get them is to add the column to an advanced list and fish through to get the ID number to then use to filter. Thanks!

**Comment by DeckardLain** [comment]
I'd love to look into this, but it seems like we don't use contract forms here, so I'll need some detailed info from you (or others who also use the forms).

When I inspect each table underneath the contract types, I see that the table IDs look like "type2937", "type2276", etc.  I'm assuming the number is the Contract Type ID.  If it's just a matter of displaying this ID number in the heading above, that's simple.

If you can send me HTML snippets of the page when there are forms listed, I can see if Contract IDs are there in a similar fashion.

**Comment by bdleblanc** [comment]
Yes, that number following “type” is the Contract Type ID. That’s exactly what we would need! (If I had realized I could just inspect the table I would have done that ages ago…haha)

I inspected the Contracts tab on the student's EMS profile and I don't see an obvious place where the Contract ID would be hiding, but honestly since that is a unique value to each individual contract it probably isn't of much value in filtering. The Contract Type ID is much more valuable. If you can add that to the header that would be great. Thank you!!

**Comment by DeckardLain** [comment]
Sorry, I was mistaken.  We _are_ using contract forms, it's just that when I first loaded the page, everything was blank.  That's Blackbaud for you...

I actually can see where the page loads the contract form info in the background, which includes ApplicationFormId, which I'm assuming is the Contract ID.  If you decide that the Contract ID would still be useful, I can work on displaying those too.  Problem is, right now there's something about the data request the page is making that I can't figure out.

I'll get the Contract Type ID displayed first, which should be done soon.

**Comment by DeckardLain** [comment]
Now implemented in Generic Edition v2.20.0.  I included some other unrelated optimizations that I hadn't put into the Generic Edition yet, so if you're planning on pulling just this change into your own script and need help identifying the relevant changes, let me know.

By the way, thanks for requesting this!  It's very similar to the reason I wanted advanced list IDs displayed--I need those a lot when setting up scripts that pull lists via SKY API.

**Comment by bdleblanc** [comment]
I had honestly given up trying to fork my own script and just went back to yours. Too much could go sideways and it wasn't worth the potential trouble to start fiddling with it and possibly really end up down a rabbit hole I didn't want to be down. I'll just keep pestering you if and when I have another thing to come up with. I will say this: over the past year Blackbaud has gotten significantly more responsive than they've ever been before, so I'm optimistic that some of this stuff will actually get implemented into the product itself and won't need to rely as much on scripts.

Thank you, as always! Have a great weekend and stay safe out there!

**Comment by DeckardLain** [comment]
That is good to hear that Blackbaud is doing more now.  I did notice script features here and there being implemented by Blackbaud or made obsolete, and I still need to clean up the script to take those out or modify them.

Pleasure to be of service. You have a great weekend too!
