### ISSUE TITLE
Clickable User ID on new event registration

### ISSUE THREAD

**Issue by bdleblanc** [DeckardLain/ON-Mod-Suite#17]
Hello again! It's your favorite pain in the posterior. I have one short request and one place where you can take something out of the code.

In the new event registration, would you be able to make it so that a user's User ID is clickable to open their profile in a new tab? See the image below - Blackbaud has it set up so that this is possible when processing applications and inquiries but since this new event registration was rushed into release despite a bevy of unaddressed issues lingering from the EAP there are all sorts of loose ends left untied. (Nope, not bitter at all.) I'm thinking you could maybe base this off the same code that links to a profile by clicking on a student's name on the Official Notes list, or possibly the code that opens a profile when clicking a user ID on an advanced list.

![image](https://github.com/DeckardLain/ON-Mod-Suite/assets/116751577/a1b4827e-9391-4cf7-9c1c-d2c6f75d366e)

And the deletion: they've added the student DOB to the processing screen for applications and file submissions, so you can remove those from the code. Please leave it in for the inquiry processing screen, because for God knows what reason they didn't add it to that screen.

Thank you SO much, Scott!!

**Comment by DeckardLain** [comment]
No problem at all!  Implemented in v2.23.1.  Did you want the ability to choose which profile page the links open to, like the drop-down that appears on advanced lists?

I actually see DOB on the inquiry processing screen too, but seeing age at a glance is helpful for our Admissions Office because there are age cutoffs for some grades, so I've replaced that feature with one that simply calculates the age based on the displayed date of birth.

**Comment by bdleblanc** [comment]
Ah, my bad - I thought the DOB on the inquiry page was part of the mod but it was actually a Blackbaud addition. Sorry about that. I just knew that it was in two places on the apps and file submission pages.

If you could include the ability to pick which part of the profile to open, that would be awesome. I'm not sure if you can do it directly on that page like you can with the advanced lists or if it would be easier to be something that you select in settings. Honestly either way is fine with me.

Thanks again!

**Comment by DeckardLain** [comment]
v2.23.2: Added a dropdown on the Process Event Registrations page that works like the one in advanced lists (remembers your choice, but for this entire area, not per event).  I also updated the Academics profile options, since they were still using the old Academics profile pages.

Thanks!
