### ISSUE TITLE
Favorite Lists is causing Core dropdowns to break 

### ISSUE THREAD

**Issue by bdleblanc** [DeckardLain/ON-Mod-Suite#19]
Hey Scott - whatever release Blackbaud put out today has caused a weird bug with Core dropdowns. The Favorite Lists area is greying out, and to be able to use the menus you have to wait for the full page to load, which in some cases takes a while. Hovering over the greyed out area causes the menu to disappear. Screenshot below - any ideas?

![Screenshot 2024-08-13 at 9 02 18 AM](https://github.com/user-attachments/assets/91a45836-9566-4952-b0e0-233f32c5ffb2)

**Comment by DeckardLain** [comment]
Thanks for pointing that out! v2.25.0 waits until one of the tiles loads before putting the advanced list favorites on the page. That should prevent this issue.

**Comment by bdleblanc** [comment]
Thanks Scott! Glad it was an easy fix - even just in a couple hours today, it was driving me bananas!!



Brian LeBlanc  Admissions Support Specialist

Thales Academy developing classical thinkers

Phone: (919) 208-9782 | Admission FAQs<https://www.thalesacademy.org/admissions/admission-faqs> | Apply Now<https://www.thalesacademy.org/admissions/admission-process>

Sent via Outlook for iOS<https://aka.ms/o0ukef>
________________________________
